stages:
  - check
  - build
  - push

check_version:
  stage: check
  image: alpine
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - "apk add yq"
  script:
    - "./check_version_and_changelog.sh"

docker_build_amd64:
  stage: build
  image: docker:dind
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - docker build --build-arg ADDON_VERSION=${CI_COMMIT_TAG} -t ${CI_REGISTRY_IMAGE}/amd64:${CI_COMMIT_TAG} .

docker_push_all:
  stage: push
  image: docker:dind
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker push ${CI_REGISTRY_IMAGE}/amd64:${CI_COMMIT_TAG}
