stages:
  - check
  - build_push

check_version:
  stage: check
  image: alpine
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - "apk add yq"
  script:
    - "./check_version_and_changelog.sh"

docker_buildx:
  stage: build_push
  image: docker:dind
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --name one-time-service-builder --use --bootstrap --driver docker-container
  script:
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --build-arg ADDON_VERSION=${CI_COMMIT_TAG} -t ${CI_REGISTRY_IMAGE}/multiarch:${CI_COMMIT_TAG} --push --provenance false .
  after_script:
    - docker buildx rm one-time-service-builder
  
#docker_homeassistant_builder:
#  stage: build
#  image: homeassistant/amd64-builder
#  script:
#    - --amd64 --aarch64 --armv7 -t .
#
# The home assistant builder currently doesn't support
# pushing to custom registries! 