name: "One Time Service"
description: "Call a service with a one time token from outside Home Assistant!"
slug: "one-time-service"
version: "0.2.0"
stage: stable
url: https://git.leon.wtf/leon/one-time-service
arch:
  - amd64
image: registry.git.leon.wtf/leon/one-time-service/{arch}

init: false
homeassistant_api: true
ingress: true
ingress_port: 8099 # default, admin dashboard
map:
  - share:rw
ports:
  1337/tcp: 1337 # public interface

options:
  public_token_base_url: null
  notify_on_token_submission: true
  notification_target: "persistent_notification.create"
schema:
  public_token_base_url: "str"
  notify_on_token_submission: "bool" 
  notification_target: "str"

panel_icon: mdi:ticket-confirmation
