name: "One Time Event"
description: "Fire an event with a one time token from outside Home Assistant!"
slug: "one-time-event"
version: "0.1.0"
stage: experimental
url: https://git.leon.wtf/leon/one-time-event
arch:
  - amd64
image: registry.git.leon.wtf/leon/one-time-event/{arch}

init: false
homeassistant_api: true
ingress: true
ingress_port: 8099 # default, admin dashboard
map:
  - share:rw
ports:
  1337/tcp: 1337 # public interface

options:
  public_token_url: null
  makros: []
schema:
  public_token_url: "url"
  makros:
    - name: "str(,50)"
      do:
        - service: "str"
          data:

panel_icon: mdi:ticket-confirmation
#panel_admin: true